#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'rabbitmq'
cookbook 'vim'
cookbook 'agora-ciudadana', path: 'cookbooks-source/agora-ciudadana'
